name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['master']
    tags: [v*]
  # release:
    # types: [published]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      SCALA_VERSION:  "2.12.15"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}


      - name: run tests
        run: ./sripts/test